name: Build_Test_Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Print Username
      run: echo ${{ github.event.pull_request.user.login }}
    
    - name: Print Href
      run: echo ${{ github.event.pull_request._links.self.href }}
